language: cpp
compiler:
  - gcc
os: linux
dist: trusty
before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev valgrind
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - cd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - which valgrind
 - sudo pip install codecov
 - cd "${TRAVIS_BUILD_DIR}"
 - ls -l
script: 
 - cd ut
 - cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON .
 - make
 - make xpjson_coverage
 - ls -l
 - ctest
 - valgrind ./xpjson_ut
branches:
  only:
    - master
addons:
  apt:
    packages:
    - cmake
after_success:
    - codecov -t 903cbedc-90af-4d3f-9af8-5d970c0821ab -X gcov